layout_spectrum: 0.5968274530023336
typography_spectrum: 0.6999430244322866
color:
  brandColors:
    - '#000000'
    - '#202040'
    - '#2F3465'
    - '#7877BE'
    - '#6563A7'
  brandStrength: 0.008709083311259747
  lightness: 0.008676966885104775
  saturation: 0.2682667395565659
  rhythmicContrast: 0.8162075933068991
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: winter
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: The North
    id: 5ccf97eb-51c5-4ca1-81c2-504e4e16ee33
    type: content
favicon: null
title: winter
purpose: []
