layout_spectrum: 0.13455769419670105
typography_spectrum: 0.03617072105407715
color:
  brandColors:
    - '#E1E6FA'
    - '#C4D7ED'
    - '#ABC8E2'
    - '#375D81'
    - '#183152'
  brandStrength: 0.061860196059569716
  lightness: 0.330078745726496
  saturation: 0.32562157860957086
  rhythmicContrast: 0.7904314710758626
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: winter
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: The North
    id: 5ccf97eb-51c5-4ca1-81c2-504e4e16ee33
    type: content
favicon: null
title: winter
purpose: []
